/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;

import Business.Enterprise.Enterprise;
import Business.Forum.Answer;
import Business.Forum.Question;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author vaibhavdhoke
 */
public class FarmerForumAnswerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FarmerForumAnswerJPanel
     */
    private JPanel userProcessContainer;
    private FarmerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Question question;
    public FarmerForumAnswerJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,FarmerOrganization organization,Question question) {
        initComponents();
//        DefaultTableModel model = (DefaultTableModel) tblAnswer.getModel();
        JTableHeader header = tblAnswer.getTableHeader();
        TableCellRenderer rendererFromHeader = header.getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        header.setFont(new Font("SansSerif", Font.BOLD, 16));
        
        
//        header.setOpaque(false);
//        header.setBackground(Color.black);
//        header.setForeground(Color.yellow);
//        tblAnswer.setModel(model);
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.question = question;
        lblQuestion.setText(question.getQuestion());
        populateAnswerTable();
    }

    public void populateAnswerTable(){
        DefaultTableModel model = (DefaultTableModel) tblAnswer.getModel();
        if(question.getAnswersList().size()>0){
            model.setRowCount(0);
            for (Answer answer : question.getAnswersList()){
                Object[] row = new Object[3];
                row[0] = answer;
                row[1] = answer.getText();
                row[2] = answer.isIsRelevant()? "Usefull": "";
                model.addRow(row);
        }
        }
        else JOptionPane.showMessageDialog(null, "No one has answered this question");
               
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnswer = new javax.swing.JTable();
        btnSubmitAnswer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdateRelevance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboUpdate = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnswer = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        tblAnswer.setFont(new java.awt.Font("Malayalam MN", 0, 14)); // NOI18N
        tblAnswer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Farmer Name", "Answer", "Relevant"
            }
        ));
        tblAnswer.setRowHeight(25);
        jScrollPane1.setViewportView(tblAnswer);
        if (tblAnswer.getColumnModel().getColumnCount() > 0) {
            tblAnswer.getColumnModel().getColumn(0).setMinWidth(200);
            tblAnswer.getColumnModel().getColumn(0).setMaxWidth(200);
            tblAnswer.getColumnModel().getColumn(1).setMinWidth(200);
            tblAnswer.getColumnModel().getColumn(1).setMaxWidth(900);
            tblAnswer.getColumnModel().getColumn(2).setMinWidth(30);
            tblAnswer.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        btnSubmitAnswer.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmitAnswer.setText("Submit");
        btnSubmitAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAnswerActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateRelevance.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateRelevance.setText("Update");
        btnUpdateRelevance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRelevanceActionPerformed(evt);
            }
        });

        jLabel1.setText("Did this Answer Help?");

        comboUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        jPanel1.setBackground(new java.awt.Color(47, 72, 147));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Question:");

        lblQuestion.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion.setText("<Q>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(765, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel3.setText("Write Answer:");

        txtAnswer.setColumns(20);
        txtAnswer.setRows(5);
        jScrollPane2.setViewportView(txtAnswer);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Farmer/FarmerHelpingFarmers.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSubmitAnswer)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnUpdateRelevance))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmitAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateRelevance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAnswerActionPerformed
        // TODO add your handling code here:
        
        if(txtAnswer.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Answer field cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
        Answer answer = new Answer();
        answer.setText(txtAnswer.getText());
        answer.setFarmerAccount(userAccount);
        question.getAnswersList().add(answer);
        
        populateAnswerTable();
        }
    }//GEN-LAST:event_btnSubmitAnswerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateRelevanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRelevanceActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAnswer.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) tblAnswer.getModel();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the Answer", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Answer answer = (Answer) tblAnswer.getValueAt(selectedRow, 0);
            if(question.getFarmerAccount().getUsername()==userAccount.getUsername()){
                String combovalue = comboUpdate.getSelectedItem().toString();
            
            if(combovalue=="Yes"){
                model.setValueAt("Useful", selectedRow, 2);
                answer.setIsRelevant(true);
            }
            else if(combovalue=="No"){
                model.setValueAt("", selectedRow, 2);
                answer.setIsRelevant(false);
            }
            
            }else {
                JOptionPane.showMessageDialog(null, "You can update for the questions which you have posted", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            
            
            
        }
        
    }//GEN-LAST:event_btnUpdateRelevanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitAnswer;
    private javax.swing.JButton btnUpdateRelevance;
    private javax.swing.JComboBox<String> comboUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JTable tblAnswer;
    private javax.swing.JTextArea txtAnswer;
    // End of variables declaration//GEN-END:variables
}
