/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Customer;

import Business.Crop.Crop;
import Business.EcoSystem;
import Business.Enterprise.AgricultureEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FarmerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerOrderWorkRequest;
import Business.WorkQueue.FarmerCropWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Farmer.FarmerWorkAreaJPanel;

/**
 *
 * @author vaibhavdhoke
 */
public class CustomerOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerOrderJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private FarmerCropWorkRequest request;
    public static final Pattern VALID_EMAIL_ADDRESS_REGEX
            = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
    
    public CustomerOrderJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,Organization organization,EcoSystem business,FarmerCropWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.request= request;
        valueLabel.setText(userAccount.getEmployee().getName());
        
        populateOrderRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnPlaceOrder = new javax.swing.JButton();
        txtProductName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFarmerName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtOrderQuantity = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setText("Product Name:");

        jLabel3.setText("Available Quantity:");

        txtQuantity.setEditable(false);
        txtQuantity.setEnabled(false);

        btnPlaceOrder.setBackground(new java.awt.Color(47, 72, 147));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        txtProductName.setEditable(false);
        txtProductName.setEnabled(false);
        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Price:");

        txtPrice.setEditable(false);
        txtPrice.setEnabled(false);

        jLabel5.setText("Farmer/Seller:");

        txtFarmerName.setEditable(false);
        txtFarmerName.setEnabled(false);

        jLabel6.setText("Order Quantity:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel7.setText("Email Address:");

        jLabel8.setText("Address:");

        jPanel1.setBackground(new java.awt.Color(47, 72, 147));

        jLabel9.setFont(new java.awt.Font("Malayalam MN", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Customize Order");

        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("<value>");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Welcome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel1.setText("$");

        jLabel10.setText("Lbs");

        jLabel12.setText("Lbs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(12, 12, 12)))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity)
                            .addComponent(txtProductName)
                            .addComponent(txtPrice)
                            .addComponent(txtFarmerName)
                            .addComponent(txtOrderQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtEmail)
                            .addComponent(txtAddress)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlaceOrder)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(258, 258, 258))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtFarmerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        public void populateOrderRequest(){
        
//        Organization org = null;
//            for(Network network : business.getNetworkList()){
//                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
//                    for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//                        if(organization instanceof CustomerOrganization){
//                            org = organization;
//                            break;
//                        }
//                    }
//                }
//            }
//            
//            System.out.println("Org "+org.getWorkQueue().getWorkRequestList());
//            FarmerCropWorkRequest fc = null;
//            List<String> cropNameList = new ArrayList<>();
//            
//            
//            for(WorkRequest workRequest : org.getWorkQueue().getWorkRequestList()){
//                if(workRequest instanceof FarmerCropWorkRequest){
//                    fc = (FarmerCropWorkRequest) workRequest;
//                    cropNameList.add(fc.getCrop().getCropName());
//                }
//            }
//            
//            List<String> cropNameWithoutDupList = cropNameList.stream()
//            .distinct()
//            .collect(Collectors.toList());
//            
//            System.out.println("Crop Name W "+cropNameWithoutDupList);
//            System.out.println("Crop Name "+cropNameList);
            txtProductName.setText(request.getCrop().getCropName());
            txtPrice.setText(String.valueOf(request.getCrop().getPrice()));
            txtFarmerName.setText(request.getSender().getUsername());
            txtQuantity.setText(String.valueOf(request.getCrop().getQuantity()));
            
    }
    
        public static boolean validate(String emailStr) {
        if (emailStr == null) {
            return false;
        }
        Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(emailStr);
        return matcher.find();
        }
        
    
    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        
        try{
            boolean isValidEmail = validate(txtEmail.getText());
            String quantRegex = "[0-9]+";
            
            if(txtOrderQuantity.getText().toString().equalsIgnoreCase("0")){
                JOptionPane.showMessageDialog(null, "You should order atleast one item");
                return;
            }
            
            if(!txtOrderQuantity.getText().matches(quantRegex)){
                JOptionPane.showMessageDialog(null, "Please enter digits in quantity");
                return;
            }
             
                if (!isValidEmail) {
                    JOptionPane.showMessageDialog(null, "Please enter a valid email address");
                    return;
                }
                
                if(txtAddress.getText().length()==0){
                    JOptionPane.showMessageDialog(null, "Please enter Address");
                    return;
                }
            
            int orderQuant = Integer.parseInt(txtOrderQuantity.getText());
           
//            if(){
//            }
            
            if(orderQuant>request.getCrop().getQuantity() || request.getCrop().getQuantity() == 0){
            
            SendMailUsingAuthentication sendMail = new SendMailUsingAuthentication();
//            sendMail.send("organic3farm@gmail.com", "organic@123",
//                            txtEmail.getText(), "Congratulations !!", "Your order is successfully sent to Farmer");
            JOptionPane.showMessageDialog(null,"Quantity not availble");
            }else{
                CustomerOrderWorkRequest customerOrderWorkRequest = new CustomerOrderWorkRequest();
        
        Organization org= null;
        for (Network network : business.getNetworkList()) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise instanceof AgricultureEnterprise) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                if (organization instanceof FarmerOrganization) {
                                    org = organization;
                                    break;
                                }
                            }
                        }
                    }
                }
        
        Crop crop = request.getCrop();
        crop.setQuantity(crop.getQuantity()-orderQuant);
        request.setCrop(crop);
        FarmerCropWorkRequest fcr=null;
//        for(WorkRequest w:request.getSender().getWorkQueue().getWorkRequestList()){
//            if(w instanceof FarmerCropWorkRequest){
//                fcr= (FarmerCropWorkRequest)w;
//                if(fcr.getCrop().getCropName().equalsIgnoreCase(request.getCrop().getCropName())){
//                    Crop c = fcr.getCrop();
//                    c.setQuantity(c.getQuantity()-orderQuant);
//                    fcr.setCrop(c);
//                }
//                
//            }
//        }
        double totalPrice = orderQuant*crop.getPrice();
        customerOrderWorkRequest.setStatus("Order Placed");
        customerOrderWorkRequest.setCropName(request.getCrop().getCropName());
        customerOrderWorkRequest.setQuantiy(Integer.parseInt(txtOrderQuantity.getText()));
        customerOrderWorkRequest.setCustomer(userAccount);
        customerOrderWorkRequest.setEmail(txtEmail.getText());
        customerOrderWorkRequest.setAddress(txtAddress.getText());
        customerOrderWorkRequest.setTotalPrice(totalPrice);
        //org.getWorkQueue().getWorkRequestList().add(customerOrderWorkRequest);
        request.getSender().getWorkQueue().getWorkRequestList().add(customerOrderWorkRequest);
        
        
        
//        List<WorkRequest> temp = new ArrayList<>();
//                for(WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()){
//                    System.out.println("inside for:"+wr);
//                    if(wr instanceof CustomerOrderWorkRequest){
//                        temp.add(wr);
//                        org.getWorkQueue().getWorkRequestList().remove(wr);
//                        userAccount.getWorkQueue().getWorkRequestList().remove(wr);
//                
//
//                }
//            }
//                System.out.println("Temp" +temp);
//                userAccount.getWorkQueue().getWorkRequestList().removeAll(temp);
//                org.getWorkQueue().getWorkRequestList().removeAll(temp);
                
            userAccount.getWorkQueue().getWorkRequestList().add(customerOrderWorkRequest);
        
            JOptionPane.showMessageDialog(null, "Order Placed Successfully");
            SendMailUsingAuthentication sendMail = new SendMailUsingAuthentication();
            sendMail.send("organic3farm@gmail.com", "organic@123",
                            txtEmail.getText(), "Congratulations !!", "Your order is successfully placed Ordered item is "+customerOrderWorkRequest.getCropName());
       
            }
        
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter quantity in proper format");
        }
        
         
        
        
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel cojp = (CustomerWorkAreaJPanel) component;
        cojp.populateCropRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFarmerName;
    private javax.swing.JTextField txtOrderQuantity;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
